config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: %i[index create]
  resources :weapons
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  enum kind: %i[knight wizard]

  def title
    "#{kind} #{nickname} ##{level}"
  end

  validates :level, numericality: { greater_than: 0, less_than_or_equal_to: 99 }
end

app/models/weapon.rb
class Weapon < ApplicationRecord
  validates :level, numericality: { greater_than: 0 }
  validates :power_base, numericality: { greater_than: 0 }
  validates :power_step, numericality: { greater_than: 0 }

  def current_power
    power_base + ((level - 1) * power_step)
  end

  def title
    "#{name} ##{level}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def create
    @user = User.create(user_params)
    redirect_to users_path
  end

  private

  def user_params 
    params.require(:user).permit(:nickname, :kind, :level)
  end
end

app/controllers/weapons_controller.rb
class WeaponsController < ApplicationController
  before_action :set_weapon, only: %i[show destroy]

  def index
    @weapons = Weapon.all
  end

  def create
    @weapon = Weapon.create(weapon_params)
    redirect_to users_path
  end

  def show; end

  def destroy
    @weapon.destroy
  end

  private

  def weapon_params
    params.require(:weapon).permit(:name, :description, :power_base, :power_step, :level)
  end

  def set_weapon
    @weapon = Weapon.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestLikeAHero</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<% @users.each do |user| %>
    <p> <%= user.title %> </p>
<% end %>

app/views/weapons/create.html.erb
<h1>Weapons#create</h1>
<p>Find me in app/views/weapons/create.html.erb</p>

app/views/weapons/delete.html.erb
<h1>Weapons#delete</h1>
<p>Find me in app/views/weapons/delete.html.erb</p>

app/views/weapons/index.html.erb
<h1>Weapons#index</h1>
<% @weapons.each do |weapon| %>
    <p> <%= weapon.title %> </p>
    <p> <%= weapon.name %> </p>
    <p> <%= weapon.description %> </p>
    <p> <%= weapon.current_power %> </p>
    <p> <%= link_to "Detalhes - #{weapon.name}", weapon_path(weapon) %> </p>
    <hr />
<% end %>

app/views/weapons/show.html.erb
<h1>Weapons#show</h1>
<p> <%= @weapon.title %> </p>
<p> <%= @weapon.name %> </p>
<p> <%= @weapon.description %> </p>
<p> <%= @weapon.current_power %> </p>